---
title: "hw3_jhk2201"
author: "joseph Kim"
date: "10/18/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(p8105.datasets)
data("instacart")
```

### Problem 1 (Description of Instacart Data)

## How many aisles are there, and which aisles are the most items ordered from? 
```{r}

max(instacart$aisle_id)

instacart1 <- instacart %>%
  group_by(aisle) %>% 
  summarise(order_amount=n()) %>% 
  arrange(desc(order_amount)) 
```
There are 134 total aisles listed in the dataframe. The aisle with the most items ordered from was fresh vegetables which had a count of 150609. 

```{r}
instacart2 <- filter(instacart1, order_amount>10000) %>% 
arrange(desc(order_amount)) 

ggplot(instacart2, aes(x = aisle, y = order_amount)) + geom_bar(stat="Identity") +
coord_flip() + labs(title = "Number of Items Ordered for Aisle Greater than 10,000")
              
```

```{r results='asis'}
instacart %>%
      filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>%
      group_by(aisle, product_name) %>%
      summarize(amount_product = n()) %>%
      arrange(aisle, desc(amount_product)) %>%
      filter(min_rank(desc(amount_product)) <4) %>%
      knitr::kable(digits = 1, caption = "The Top Three Most Popular Items Sold in ")
```

```{r}
instacart %>%
   mutate(order_dow = recode(order_dow,
                            '0' = 'Sunday',
                            '1' = 'Monday',
                            '2' = "Tuesday",
                            '3' = "Wednesday",
                            '4' = "Thursday",
                            '5' = "Friday",
                            '6' = "Saturday")) %>%
  group_by(product_name, order_dow) %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  summarize(mean_hour_order = mean(order_hour_of_day)) %>%
  pivot_wider(instacart, 
  names_from = order_dow, 
  values_from = product_name)

```

```{r}
data("brfss_smart2010")

behavioral_health = brfss_smart2010 %>%
    janitor::clean_names() %>%
    filter(topic == "Overall Health") %>%
    filter(response %in% c("Excellent", "Very Good", "Good", "Fair", "Poor")) %>%
    mutate(response = as.factor(response)) %>%
    mutate(response = forcats::fct_relevel(response, c("Poor", "Fair", "Good", "Very good", "Excellent")))
```


